import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/local-UI/Navbar/Navbar";
import { ThemeProvider } from "@/providers/ThemeProviders";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/local-UI/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(inter.className, "dark")}
      style={{
        colorScheme: "dark",
      }}
    >
      <body>
        <ClerkProvider>
          <ThemeProvider>
            <div className=" flex min-h-screen w-full flex-col items-center dark:bg-black">
              <Toaster />
              <Navbar />
              <main className=" flex flex-grow w-full pt-16 justify-center dark:bg-neutral-950 items-center">
                {children}
              </main>
              <Footer />
            </div>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
